config/routes.rb
Rails.application.routes.draw do

   resources:posts do
     resources :comments
   end
   
  root "posts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	validates_presence_of :title
	#validates_length_of :title { minimum: 4}
	validates_presence_of :body

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to root_path
	end


	private
		def post_params
			params.require(:post).permit(:title, :body)
		end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div>
	<p><strong><%= comment.name %></strong></p>
	<p><%= comment.body %></p>
	<p><%= time_ago_in_words(comment.created_at) %> Ago</p>

	<p><%= link_to 'Delete', [comment.post, comment], method: :delete %></p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p><br>

	<p>
		<%= f.submit %>
	</p>
		
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h4><%= pluralize(@post.errors.count, "error") %> in this Post</h4>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %><br> 
		<%= f.text_area :body, rows: 10, cols: 50 %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>








<!-- 

_comments.html.erb -->

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post_wrapper">
	<h2 class="title"><%= link_to post.title,post %></h2>
	<p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
</div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h4><%= pluralize(@post.errors.count, "error") %> in this Post</h4>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %><br> 
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/show.html.erb
<h1 class="title">
	<%= @post.title %>
</h1>

<p class="date">
	Submitted <%= time_ago_in_words(@post.created_at) %> Ago
	|| <%= link_to 'Edit', edit_post_path(@post) %>
	|| <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'This post will no longer exist.Are you sure?'} %>
</p>

<p class="body">
	<%= @post.body %>
</p>

<div id="comments">
	<h2><%= @post.comments.count %> Comments </h2>
	<%= render @post.comments %>

	<h3>Add a comment:</h3>
	<%= render "comments/form" %>
</div>